---
version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/infra" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - "mtngtnsh"
    labels:
      - "dependencies"
      - 'npm'
