---
version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/infra" # Location of package manifests
    schedule:
      interval: "monthly"
    reviewers:
      - "motoish"
    labels:
      - "dependencies"
      - 'npm'

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"