---
version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/infra"
      - "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "11:00"
      timezone: "Asia/Tokyo"
    groups:
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
    commit-message:
      prefix: "npm"
      prefix-development: "dependabot"
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "motoish"
    labels:
      - "dependencies"
      - "npm"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
