---
name: Mark and close stale pull-requests
on:
  schedule:
    - cron: "50 8 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-pr-stale: 60
          days-before-pr-close: 7
          stale-pr-message: |
            "This pr has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs."
