---
services:
  localstack:
    image: localstack/localstack:stable
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3,secretsmanager,sqs
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=ap-northeast-1
  database:
    image: postgres:16-alpine3.20
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - backend-database:/var/lib/postgresql/data
      - ./test/utils/db-creation.sql:/docker-entrypoint-initdb.d/db-creation.sql
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: r54cyLQkblA7aJ6

volumes:
  backend-database:
